CC=javac

WilliamRitchieA3Chess:
	$(CC) ChessController.java ChessTextGraphics.java Game.java GameDisplay.java GamePiece.java Main.java Pawn.java Queen.java King.java Bishop.java Knight.java Rook.java ChessPlayer.java AI.java MoveData.java WindowedGraphics.java VisualChessGraphics.java